version: 2.1

executors:
  npm:
    docker:
    - image: node:26.7.0
      auth:
        username: $DOCKER_LOGIN
        password: $DOCKER_ACCESSTOKEN
  docker-publisher:
    environment:
      IMAGE_NAME: openftth/frontend
    docker:
    - image: circleci/buildpack-deps:stretch
      auth:
        username: $DOCKER_LOGIN
        password: $DOCKER_ACCESSTOKEN

jobs:
  build-app:
    executor: npm
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: NPM run build
          command: npm run build

  build-docker-image:
    executor: docker-publisher
    steps:
     - checkout
     - setup_remote_docker:
         version: default
     - run:
         name: Build Docker image
         command: |
            docker build -t $IMAGE_NAME:latest .
     - run:
         name: Archive Docker image
         command: docker save -o image.tar $IMAGE_NAME
     - persist_to_workspace:
         root: .
         paths:
          - ./image.tar

  docker-publish-image:
    executor: docker-publisher
    steps:
     - setup_remote_docker:
         version: default
     - attach_workspace:
         at: /tmp/workspace
     - run:
         name: Load archived Docker image
         command: docker load -i /tmp/workspace/image.tar
     - run:
         name: Publish Docker Image to Docker Hub
         command: |
           echo "$DOCKER_ACCESSTOKEN" | docker login -u $DOCKER_LOGIN --password-stdin
           IMAGE_TAG=${CIRCLE_TAG}
           docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
           docker push $IMAGE_NAME:latest
           docker push $IMAGE_NAME:$IMAGE_TAG

workflows:
  build-test-upload_image:
    jobs:
      - build-app:
          context: docker
          filters:
            tags:
              only: /.*/
      - build-docker-image:
          context: docker
          filters:
            tags:
              only: /.*/
      - docker-publish-image:
          context: docker
          requires:
           - build-docker-image
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
